version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=BharatFD.settings
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7.0  # Official Redis image
    ports:
      - "6379:6379"
